site_name: Public ODM Docs
repo_name: tropnikovvl/public-odm-docs
repo_url: https://github.com/tropnikovvl/public-odm-docs
edit_uri: edit/main/docs/
strict: true

nav:
  - Home:
    - Welcome: README.md
  - Packages to install:
    - Genestack python client: 00_Packages_to_install/1_Genestack_python_client/README.md
    - Genestack auxiliary scripts: 00_Packages_to_install/2_Genestack_auxiliary_scripts/README.md
  - Users:
      - User_creation: 01_Users/User_creation/README.md

plugins:
  - search
theme:
  name: material
  language: en
  # favicon: assets/images/fav.svg
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  # custom_dir: docs/theme_overrides
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js